/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+exte_55e5142fb98ed1ed19af879d65167bd3/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+exte_55e5142fb98ed1ed19af879d65167bd3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UColorModeButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+exte_55e5142fb98ed1ed19af879d65167bd3/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
  }
}
